DAY=$1
echo "day = $DAY"
mkdir -p "advent/src/dk/alfabetacain/advent_of_code/day$DAY"
MYFILE="advent/src/dk/alfabetacain/advent_of_code/day$DAY/Day$DAY.scala"
echo "package dk.alfabetacain.advent_of_code.day$DAY" > "$MYFILE"
echo "" >> "$MYFILE"
echo "object Day$DAY {" >> "$MYFILE"
echo "" >> "$MYFILE"
echo "def puzzle1(): Unit = {" >> "$MYFILE"
echo "" >> "$MYFILE"
echo "" >> "$MYFILE"
echo "}" >> "$MYFILE"
echo "" >> "$MYFILE"
echo "" >> "$MYFILE"
echo "def puzzle2(): Unit = {" >> "$MYFILE"
echo "" >> "$MYFILE"
echo "}" >> "$MYFILE"
echo "" >> "$MYFILE"
echo "}" >> "$MYFILE"
mkdir -p "advent/resources/day$DAY"
